# Generated by Django 4.0.1 on 2022-01-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=150)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('profession', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
                ('working_instituition', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('like', models.ManyToManyField(blank=True, related_name='liking', to='user.User')),
                ('match', models.ManyToManyField(blank=True, related_name='matched', to='user.User')),
            ],
        ),
    ]
